### ISSUE TITLE
TypeScript versioning issue

### ISSUE THREAD

**Issue by grevory** [gangachris/githubionic#41]
Trying to install and serve this just to see it in action is not possible based on the instructions in the README.

When I run `npm run build` which seems necessary before serving I get an error about `.tmp/app/main.prod.ts` is missing. Which it is. The solution seems to be to downgrade to TSv.2.0.3 - [See Issue](https://github.com/driftyco/ionic-app-scripts/issues/197)

I did that but now all of my versions are out of sync. Can you tell me what versions of ionic, cordova, TS, et. al. you are running so I can match? Using the latest versions based on the `package.json` does not work for a fresh install.

Thanks.

**Comment by gangachris** [comment]
@grevory I'm working with RC.0. If you installed ionic recently, it's working with RC1, which made changes to the `package.json` file...  so this may be the issue. Will look at it and make neccesary changes

**Comment by gangachris** [comment]
@grevory updated the `package.json`. Works fine now. Thanks for the update. If it works fine for you, you can close the issue.

**Comment by grevory** [comment]
Fixed! Thank you!
