### ISSUE TITLE
Missing ionic.config.json?

### ISSUE THREAD

**Issue by rwdietrich** [gangachris/githubionic#42]
On Windows 10 I cloned the repo, cd'd to the dir, and did `npm install` (the other tools were already installed). I then tried to serve the app and got the following:
`PS C:\build\ionic\githubionic> ionic build
Couldn't find ionic.config.json file. Are you in an Ionic project?
PS C:\build\ionic\githubionic>`

Is there a step missing in the readme or a missing file?

**Comment by grevory** [comment]
I copied it from /Users/.ionic/ionic.config to the project folder. Worked for me. 

Not sure where your user root is on Windows.

**Comment by rwdietrich** [comment]
Guess I expected it to be checked into github as part of the configuration. Looking at the ionic.config.json file you get when you create a project using the sidebar template, it's pretty simple:
`{
  "name": "sidemenu",
  "app_id": "",
  "v2": true,
  "typescript": true
}`

**Comment by gangachris** [comment]
Thanks @rwdietrich for pointing it out. I've added the file.
